Finally time to start adding Vaadin code to our application!

Consider `grails-app/vaadin/vaadin/VaadinGrailsUI.groovy` to be your Vaadin
controller / dispatcher as it will help you understand the Vaadin flow. Our `init()`
method is the applications entry point to Vaadin itself, this is your top level view
essentially. From here you can setup navigation and other whole app view components.

Our `VaadinGrailsUI.groovy` as it currently is, is great for a
single page web application but its not the most flexible if we want to add navigation
components or other pages later on. With this in mind we are going to make it a bit more
flexible using views. Using views is also beneficial in helping keep our Vaadin frontend
well organized.

NOTE: For more information on views and navigation with Vaadin look
https://vaadin.github.io/spring-tutorial/#_views_and_navigation_with_vaadin_spring[here].

[source,groovy]
./grails-app/vaadin/vaadin/VaadinGrailsUI.groovy
----
include::{sourceDir}/grails-app/vaadin/vaadin/VaadinGrailsUI.groovy[]
----

<1> We add the `@Title` annotation to give our window / tab a nice name
<2> Add `@SpringViewDisplay` so we can use views
<3> Along with and `implements ViewDisplay` to our class
<4> Next create an additional panel for our UI
<5> Initial entry point into our Vaadin View
<6> Helper method for building our header
<7> Additional function required for using views; dynamically controls setting our view components

==== Whats really going on here ...
In simple terms, we switch from
HorizontalLayout to a VerticleLayout and then we `setContent` to our root content.
Following setting up our root we setup our view to give us some added flexibility for
expanding our application later. Once we have built `springViewDisplay` we add it to
our root context. It is important to note that where you do something in Vaadin is
important and not, all at the same time.

- ie. `setContent(root)` is fine in its current location but could also be the last line
in the method, its position does not matter.
- ie. If we move `root.addComponent(this.buildHeader())` below where we add our panel,
our header is now on the bottom.

TIP: `init()` can get quite large quite fast so it is best to break out UI components
into their own methods like `buildHeader()` to keep your files clear and concise.

