Next lets create our service layer for our application.

[source,bash]
----
  $ cd src/main/groovy/demo/service
  $ touch MakeService
  $ touch MakeServiceImpl
  $ touch ModelService
  $ touch ModelServiceImpl
  $ touch VehicleService
  $ touch VehicleServiceImpl
----

Now let’s edit our service classes under src/main/groovy/demo/service.
We’ll add a `list()` method to all of the classes. This method will have the following additional annotation.

- @Transactional(readOnly = true) - good practice to have on methods that only return data

[source,groovy]
./src/main/groovy/demo/service/MakeService.groovy
----
include::{sourceDir}/src/main/groovy/demo/service/MakeService.groovy[]
----

[source,groovy]
./src/main/groovy/demo/service/MakeServiceImpl.groovy
----
include::{sourceDir}/src/main/groovy/demo/service/MakeServiceImpl.groovy[]
----

[source,groovy]
./src/main/groovy/demo/service/ModelService.groovy
----
include::{sourceDir}/src/main/groovy/demo/service/ModelService.groovy[]
----

[source,groovy]
./src/main/groovy/demo/service/ModelServiceImpl.groovy
----
include::{sourceDir}/src/main/groovy/demo/service/ModelServiceImpl.groovy[]
----

[source,groovy]
./src/main/groovy/demo/service/VehicleService.groovy
----
include::{sourceDir}/src/main/groovy/demo/service/VehicleService.groovy[]
----

[source,groovy]
./src/main/groovy/demo/service/VehicleServiceImpl.groovy
----
include::{sourceDir}/src/main/groovy/demo/service/VehicleServiceImpl.groovy[]
----

Additionally all our service classes make use of the `@Service('someName')` annotation.
This annotation tells Spring what our services are called so it can properly map our
dependency injection.