include::{commondir}/common-requirements.adoc[]

If you want to start from scratch, create a new Grails 3 app using the Vaadin profile:

WARNING: It is recommended to create your app with a single word name when using this profile.
Currently there is an issue when using names like `vaadin-grails` that when creating the
package name, import in the `/grails-app/vaadin/vaadin/VaadinGrailsUI.groovy` it
inserts a `/` instead of a `.`. If you wish to use a `-` feel free but remember you will
need to manually update the package name in `VaadinGrailsUI.groovy`.

[source,bash]
----
grails create-app vaadin --profile me.przepiora.vaadin-grails:web-vaadin8:0.2
----

NOTE: Additionally this profile currently generates the app using gradle wrapper 3.4.1. This
works just fine but in our code it is upgraded to 3.5. If you wish to upgrade your example
to version 3.5 as well, please make the following update and run the following command.

[source,groovy]
.gradle.properties
----
include::{sourceDir}/gradle.properties[indent=0,lines="3..3"]
----

Once you have updated the version, execute the following command. When it completes your
gradle version will be up to date.

[source,bash]
----
$ gradle wrapper
----